# Generated by Django 3.2.4 on 2021-07-02 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('la_galerie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=100)),
            ],
        ),
    ]
